module.exports = {
  apps: [
    {
      name: 'rental-web',
      script: 'node_modules/.bin/next',
      args: 'start',
      cwd: __dirname,
      env_file: '.env.local',
      autorestart: true,
      error_file: './logs/web-error.log',
      out_file: './logs/web-out.log',
    },
    {
      name: 'rental-telegram',
      script: 'node_modules/.bin/tsx',
      args: 'telegram-bot.ts',
      cwd: __dirname,
      autorestart: true,
      error_file: './logs/telegram-error.log',
      out_file: './logs/telegram-out.log',
    },
    {
      name: 'rental-whatsapp',
      script: 'node_modules/.bin/tsx',
      args: 'whatsapp-bot.ts',
      cwd: __dirname,
      autorestart: true,
      error_file: './logs/whatsapp-error.log',
      out_file: './logs/whatsapp-out.log',
    },
    {
      name: 'rental-whatsapp-observer',
      script: 'node_modules/.bin/tsx',
      args: 'whatsapp-observer.ts',
      cwd: __dirname,
      autorestart: true,
      error_file: './logs/whatsapp-observer-error.log',
      out_file: './logs/whatsapp-observer-out.log',
    },
  ],
};
